const data = {
    actions: [
        {
            _id: "001",
            title: "The Expendables",
            synopsis: "A group of mercenaries is double-crossed during a mission and are approached by Church to overthrow the ruthless dictator of a South American country. It isn't long before the men realise things aren't quite as they appear, finding themselves caught in a dangerous web of betrayal.",
            cast: "Sylvester Stallone, Jason Statham, Terry Crews, Jet Li",
            genre: "Action, Adventure",
            rating: "R",
            year: "2010",
            duration: "2h 10m",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628315418/netflix-clone/images/ex_yqqm5p.webp",
            bannerImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628553382/netflix-clone/header-images/1957840_zxdfff.jpg",
            video: "https://res.cloudinary.com/dwumhctz9/video/upload/v1628488844/netflix-clone/videos/The_Expendables_-_Official_Trailer_1_HD_gt68hp.mp4"
        },
        {
            _id: "002",
            title: "Hitman's Wife's BodyGuard",
            synopsis: "Still unlicensed and under scrutiny, Bryce is forced into action by Darius's even more volatile wife. Soon, all three are in over their heads when a madman's sinister plot threatens to leave Europe in total chaos.",
            cast: "SSamuel L Jackson, Ryan Reynolds, more",
            genre: "Action, Crime Film, Comedy, Adventure",
            rating: "R",
            year: "2021",
            duration: "2h 57m",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628316551/netflix-clone/images/hitman_s_wife_bfykry.jpg",
            bannerImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628315308/netflix-clone/header-images/hit_fhgqed.jpg",
            video: "https://res.cloudinary.com/dwumhctz9/video/upload/v1628315250/netflix-clone/videos/hit_mugrsv.mp4"
        },
        {
            _id: "003",
            title: "Den of Thieves",
            synopsis: "Nick O'Brien is the hard-drinking leader of the Regulators, an elite unit of the Los Angeles County Sheriff's Department. Ray Merrimen is the recently paroled leader of the Outlaws, a gang of ex-military men who use their expertise and tactical skills to evade the law. O'Brien, Merrimen and their crews soon find themselves on a direct collision course as the criminals hatch an elaborate plan for a seemingly impossible heist -- the city's Federal Reserve Bank.",
            cast: "Gerard Butler, 50 Cent, O'shea Jackson Jr.",
            genre: "Action, Crime Film, Comedy, Adventure",
            rating: "R",
            year: "2018",
            duration: "2h 38m",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628315419/netflix-clone/images/den_oprsav.webp",
            bannerImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628755803/netflix-clone/header-images/den-of-thieves_oggyj5.jpg",
            video: ""
        },
        {
            _id: "004",
            title: "Iron Man 3",
            synopsis: "Plagued with worry and insomnia since saving New York from destruction, Tony Stark is now more dependent on the suits that give him his Iron Man persona -- so much so that every aspect of his life is affected, including his relationship with Pepper.",
            cast: "Robert Downey Jr., Gwyneth Paltrow, Guy Pearce, Don Cheadle",
            genre: "Action, Comedy, Adventure, Superhero",
            category: "action",
            rating: "Pg-13",
            year: "2013",
            duration: "2h 11m",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628315419/netflix-clone/images/iron_iofg2w.webp",
            bannerImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628827365/netflix-clone/header-images/ironman3_lrwq0p.jpg",
            video: "https://res.cloudinary.com/dwumhctz9/video/upload/v1628827497/netflix-clone/videos/Iron_Man_3_--_Official_Trailer_UK_Marvel___HD_1_ruklln.mp4"
        },
        {
            _id: "005",
            title: "The Hitman's BodyGuard",
            synopsis: "The world's top protection agent is called upon to guard the life of his mortal enemy, one of the world's most notorious hit men. The relentless bodyguard and manipulative assassin have been on the opposite end of the bullet for years and are thrown together for a wildly outrageous 24 hours.",
            cast: "Ryan Reynolds, Samuel L. Jackson, Salma Hayek, Elodie Yung",
            genre: "Action, Comedy, Thriller, Adventure",
            category: "action",
            rating: "R",
            year: "2017",
            duration: "1h 58m",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628315419/netflix-clone/images/hitman_bd_xqzyfq.webp",
            bannerImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628828470/netflix-clone/header-images/848302-66549-jivcvbbgtp-1503546914_aeectn.jpg",
            video: "https://res.cloudinary.com/dwumhctz9/video/upload/v1628828284/netflix-clone/videos/The_Hitman_s_Bodyguard_Red_Band_Trailer_1_2017_Ryan_Reynolds_Samuel_L._Jackson_Action_Movie_HD_suqssn.mp4"
        },
        {
            _id: "007",
            title: "John Wick 3: Parabellum",
            synopsis: "After gunning down a member of the High Table -- the shadowy international assassin's guild -- legendary hit man John Wick finds himself stripped of the organization's protective services. Now stuck with a $14 million bounty on his head, Wick must fight his way through the streets of New York as he becomes the target of the world's most ruthless killers.",
            cast: "Keanu Reeves, Halle Berry, Ian McShane, Laurence Fishburne",
            genre: "Action, Thriller, Crime film",
            category: "action",
            rating: "R",
            year: "2019",
            duration: "2h 23m",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628317621/netflix-clone/images/john_wick_3_tkckvs.webp",
            bannerImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628832340/netflix-clone/header-images/john_wick_aod2yp.jpg",
            video: "https://res.cloudinary.com/dwumhctz9/video/upload/v1628829075/netflix-clone/videos/John_Wick__Chapter_3_-_Parabellum_2019_Movie_New_Trailer_Keanu_Reeves_Halle_Berry_wgpg2p.mp4"
        },
        {
            _id: "008",
            title: "Inside Man",
            synopsis: "A tough detective (Denzel Washington) matches wits with a cunning bank robber (Clive Owen), as a tense hostage crisis is unfolding. Into the volatile situation comes a woman named Madaline (Jodie Foster), a mysterious power broker who has a hidden agenda and threatens to push a tense situation past the breaking point.",
            cast: "Denzel Washington, Clive Owen, Jodie Foster, Christopher Plummer",
            genre: "Drama, Thriller, Heist, Crime Film",
            category: "drama",
            rating: "R",
            year: "2006",
            duration: "2h 9m",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628391905/netflix-clone/images/Inside-Man-poster_r36qwo.jpg",
            bannerImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628915369/netflix-clone/header-images/inside_oc8mns.jpg",
            video: "https://res.cloudinary.com/dwumhctz9/video/upload/v1628915823/netflix-clone/videos/videoplayback_3_ikwoz0.mp4"
        },
        {
            _id: "009",
            title: "Star Trek",
            synopsis: "Aboard the USS Enterprise, the most-sophisticated starship ever built, a novice crew embarks on its maiden voyage. Their path takes them on a collision course with Nero, a Romulan commander whose mission of vengeance threatens all mankind. If humanity would survive, a rebellious young officer named James T. Kirk and a coolly logical Vulcan named Spock must move beyond their rivalry and find a way to defeat Nero before it is too late.",
            cast: "John Cho, Simon Pegg, Chris Pine, Zachary Quinto",
            genre: "Adventure, Action fiction, Science fiction",
            category:"action",
            rating: "PG-13",
            year: "2009",
            duration: "2h 7m",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628392198/netflix-clone/images/shuttle-pod-st09-header_vu47bp.jpg",
            bannerImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628916316/netflix-clone/header-images/Star-Trek_rzar4z.jpg",
            video: "https://res.cloudinary.com/dwumhctz9/video/upload/v1628916400/netflix-clone/videos/Star_Trek_2009_Official_Trailer_-_Chris_Pine_Eric_Bana_Zoe_Saldana_Movie_HD_wv86ik.mp4"
        },
        {
            _id: "010",
            title: "Spider Man: Far From Home",
            synopsis: "Peter Parker's relaxing European vacation takes an unexpected turn when Nick Fury shows up in his hotel room to recruit him for a mission. The world is in danger as four massive elemental creatures -- each representing Earth, air, water and fire -- emerge from a hole torn in the universe. Parker soon finds himself donning the Spider-Man suit to help Fury and fellow superhero Mysterio stop the evil entities from wreaking havoc across the continent.",
            cast: "Tom Holland, Samuel L. Jackson, Zendaya, Cobie Smulders",
            genre: "Action, Adventure, Superhero, Science fiction",
            category: "action",
            rating: "PG-13",
            year: "2019",
            duration: "2h 9m",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628392299/netflix-clone/images/85-856770_spider-man-far-from-home-imcdb_koydqp.jpg",
            bannerImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628917698/netflix-clone/header-images/spider_ypxhsi.jpg",
            video: "https://res.cloudinary.com/dwumhctz9/video/upload/v1628917841/netflix-clone/videos/SPIDER-MAN__FAR_FROM_HOME_-_Official_Trailer_xv9erh.mp4"
        },
        {
            _id: "011",
            title: "Snow Piercer",
            synopsis: "Survivors of Earth's second Ice Age live out their days on a luxury train that ploughs through snow and ice. The train's poorest residents, who live in the squalid caboose, plan to improve their lot by taking over the engine room.",
            cast: "Chris Evans, Song Kang-ho, Tilda Swinton, Jamie Bell",
            genre: "Action, Science fiction, Thriller, Aventure",
            category: "action",
            rating: "R",
            year: "2013",
            duration: "2h 6m",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628392732/netflix-clone/images/weinstein-RAD1910-Full-Image_GalleryCover-en-US-1476120328081._UY500_UX667_RI_TTW__uol6hq.jpg",
            bannerImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628918036/netflix-clone/header-images/snow_faiunp.jpg",
            video: "https://res.cloudinary.com/dwumhctz9/video/upload/v1628918165/netflix-clone/videos/Snowpiercer_Official_US_Release_Trailer_1_2014_-_Chris_Evans_Movie_HD_q9civr.mp4"
        }
    ],
    comedies: [
        {
            _id: "001",
            title: "Hitch",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628396270/netflix-clone/images/AAAABU0xsqOE5A2qPh-4SVx5f5rHfxNVJVgmwRua3fh1Bj_4gtm4m471mQAALlfKY66xxmoMi5nDNa1gZgpovvnudlMRNQU_zyzw2n.webp",
            bannerImage: "",
            video: ""
        },
        {
            _id: "002",
            title: "Sex And The City: The Movie",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628396269/netflix-clone/images/AAAABaZ3UDh3_3P_RHfS2mrNwigyAUaYxf3nWmhFmBAMpjqQ3GHgIt0v15Uen9AN2gtzlcQ4pWBT6z9YoL1UGIS4ubGUWOY_gxcwoh.webp",
            bannerImage: "",
            video: ""
        },
        {
            _id: "003",
            title: "Blended",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628396270/netflix-clone/images/AAAABfG193aKHXGYek_NlApWsxb7M_d-oX-KRtzBD69-zd3sfRS4kDAAxdOmXDc_aoiVRt-HvscrdyCf3qfVhNP2jkoFOjQ_hsbww9.webp",
            bannerImage: "",
            video: ""
        },
        {
            _id: "004",
            title: "Bad Boys for Life",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628395389/netflix-clone/images/https___s3-images.ladbible.com_s3_content_2cc9c0315d703f8469218df5b0739853_r4wv4k.jpg",
            bannerImage: "",
            video: ""
        },
        {
            _id: "005",
            title: "Thunder Force",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628396291/netflix-clone/images/AAAABXn2suyLSb-wHjAF3_b6mGnDR5cmcXvkpkCW6QWXo61gL-SEqX6-Yo2Px9VGN-tkyNO62bfpQ87fcOsvGDjnZ4szuCBhnYUrLb5uYsR0-KMYa2Dfr5feYsd8SQAG_kyekhz.jpg",
            bannerImage: "",
            video: ""
        },
        {
            _id: "005",
            title: "The Bounty Hunter",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628396291/netflix-clone/images/AAAABVN6Awn8QLc4X1gJ3EscB0XMGbZXCNuvyY0rhUpYW6VZUnLysEo6_x1Z4Qo854mPT_wdvtTtqze9opoMB-PlUcaWa0g_kcotgb.webp",
            bannerImage: "",
            video: ""
        },
        {
            _id: "006",
            title: "Green Book",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628396270/netflix-clone/images/AAAABU3i0n9GypObbMaZ2HiVD7RyzulaIV3AHhNESv9xF5U2zU4Q-FvVg-GrtvgdDLX5ZMSeyeb4z2d63aW6oC17abfQ2s8_vqidfx.webp",
            bannerImage: "",
            video: ""
        },
        {
            _id: "007",
            title: "Friends With Benefits",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628396270/netflix-clone/images/AAAABTcBPfyjb7W9RwP7d_gjMWt7pWBgeTrS_jwS1T98LixX6EGXJUW9YOY_necCpr1Ynu_u9dKb1ucqE9DV6B5pDAtvZ5s_uyg7xc.webp",
            bannerImage: "",
            video: ""
        },
        {
            _id: "008",
            title: "True Memoirs Of An International Assassin",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628396270/netflix-clone/images/AAAABTLggh4mPf7ALD3IwHDSbhkXyqZ2VV9pitk29FfzAELEAUtvmwqd_Z96TH54MbVBTJKFRC1kBrxbg2iDmKbpvxiPjBpl1_5EIIeYS67gJ8cR8ZXfvykbTzRz2OIa_vsbz2r.jpg",
            bannerImage: "",
            video: ""
        },
        {
            _id: "009",
            title: "Hancock",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628396269/netflix-clone/images/AAAABd-UN8-tILbIDsOSBVDheBpJe3nKlWKjZEcK55lBVCXyeTaqJqQR3X3qpE56161Ee7pUN5_HDlEeGFcqlgk1k1l84c8_nuqqt4.webp",
            bannerImage: "",
            video: ""
        },
        {
            _id: "010",
            title: "Bad Boys",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628396269/netflix-clone/images/AAAABe1Saoy0nvPxEquE2iTawcyKTdEV-gTK1h9XgqhfUZ9v6N1T-qx2VQ1YwtGv4RBhV3-UeeFJ2mwoFhv-pZNZXN7ZU-o_zikzgk.webp",
            bannerImage: "",
            video: ""
        },
        {
            _id: "011",
            title: "The Green Hornet",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628396269/netflix-clone/images/AAAABcyjGjpxLtS5OQdp4b2Qd9ZwDM3EaCpavzbPq4xiMXRNc5POdKp7h7RBkG4mjY4m4pGSJbrRg1hBJwKAlJRgwVzSLlE_s1o3ns.webp",
            bannerImage: "",
            video: ""
        },
        {
            _id: "012",
            title: "Baby Driver",
            synopsis: "Baby, a music-loving orphan also happens to be the prodigiously talented go-to getaway driver for heist mastermind Doc. With the perfect soundtrack picked out for each and every job, Baby ensures Doc's violent, bank-robbing cronies get in and out of Dodge before it's too late. He's not in it for the long haul though, hoping to nail one last job before riding off into the sunset with beautiful diner waitress Debora. Easier said than done.",
            cast: "Ansel Elgort, Kevin Spacey, Lily James, Jamie Foxx",
            genre: "Drama, Action, Comedy, Adventure",
            category: "action",
            rating: "R",
            year: "2017",
            duration: "1 55m",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628397164/netflix-clone/images/AAAABbDWUjuiODCBxQwBZuzN1i5A872V7gKFOwJoIjsHBNFuCxMb0tqg3kKPhUPCsesYJGOYIzpjq37yO0ZRDww4VjrF8k0_mdjtgn.webp",
            bannerImage: "",
            video: ""
        }
    ],
    dramas:[
        {
            _id: "001",
            title: "Snowden",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628397866/netflix-clone/images/AAAABZp5KJeJ3OR1LXgPWhGIurZdQPOlHb4IMuMXf7YAmt1O4Mlwz3xnlAfq5Pf84OgWUKwAFbpSCQPnz6X0xXp9zFcfwSE_ghbojq.webp",
            bannerImage: "",
            video: ""
        },
        {
            _id: "002",
            title: "The IrishMan",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628397865/netflix-clone/images/AAAABZg87Iq_QSvfjFrPIv1sZFQL2hJDIe0Wa57qb1sfx7lYDoSAlSkP0xaVMklWG-_ZDEMxtsFo_Fo1JKYLs7nKzpcVuxZwCf9IFl_5KtTzgk8MgTg_r6Z558I-EFHS_tcoeig.jpg",
            bannerImage: "",
            video: ""
        },
        {
            _id: "003",
            title: "Bird Box",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628397835/netflix-clone/images/AAAABVBNrSAYO_6S-AZkSI9Wpd-7D1OWOedvWxHTPDYEcFGnoFt0nRjdPkUGgsg8Eq2KhB8d9MPKr7cAM1D9RUHKDZ2y0CnmRucS5z1-K_Kdrf9pWt8-2nthn8C9BJ0L_zzkhej.jpg",
            bannerImage: "",
            video: ""
        },
        {
            _id: "004",
            title: "Patriots Day",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628397835/netflix-clone/images/AAAABW923HcPUgQ-YiOrZ1Rd5yhyXk073f3jqZI-yWFXAX_cUIJpht8_ddRX76G119U8cKtWvZyLmt1zoHtX6XpG5ETv-Is_ydzata.webp",
            bannerImage: "",
            video: ""
        },
        {
            _id: "005",
            title: "The HighWayMen",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628397816/netflix-clone/images/AAAABUBbEAoG288c-3GIdEIC4NSjYjxeV_n84UfugXGHN1nPBw1kHjcSpaO1oOZ19TVtJFYNHPQ0JPUYahlTi4tTqUtAWFH0flcGGNkLDV4CiyJO2z-FrM8IdmUuSd5B_ui9s5j.jpg",
            bannerImage: "",
            video: ""
        },
        {
            _id: "006",
            title: "FatherHood",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628397816/netflix-clone/images/AAAABTCNKW7q9FP80WnnqjnJUHM8KXNC6DB-QcTgysMRokKr1lPa8JH1cb1G9MNrbW8UzXh1Qja8FBMXX-6bklHFhCQvsjXJY2KO3ds3RMDjE_TN1CKviKB_z_O_PDaT_doybha.jpg",
            bannerImage: "",
            video: ""
        },
        {
            _id: "007",
            title: "Scarface",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628397787/netflix-clone/images/AAAABRK27gTmbHM7Atg4O1S5E7iDvmgUGRsylJ7sabtvyS522-3ZfLizCZasSnOueL3KPWqNmyPdmi6ofLesfF-5_0OaB70_visc8s.webp",
            bannerImage: "",
            video: ""
        },
        {
            _id: "008",
            title: "Broken City",
            synopsis: "",
            cast: "",
            genre: "",
            rating: "",
            year: "",
            duration: "",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628397787/netflix-clone/images/AAAABR-TeNOZiSbGl6BYriZ3eeQtFaZPgCaZ13McKFVmLnuzgPPMmxzbCzzGNLzhpR2McjCRvzQYMJKsM3_kR9J9KttgiFI_kugqsd.webp",
            bannerImage: "",
            video: ""
        },
        {
            _id: "009",
            title: "Law Abiding Citizen",
            synopsis: "Clyde Shelton is an honorable family man, until the day his wife and daughter are murdered in a home invasion. He hopes for justice, but a rising prosecutor named Nick Rice cuts a deal with one of the killers in exchange for testimony.",
            cast: "Gerard Butler, Jamie Foxx, Regina Hall",
            genre: "Drama, Crime Thriller, Crime Fiction",
            category: "drama",
            rating: "R",
            year: "2009",
            duration: "1h 58m",
            smallImage: "https://res.cloudinary.com/dwumhctz9/image/upload/v1628397768/netflix-clone/images/AAAABdBmRO8DgpVur-_3XWMzt2DDrxV27qRZ_DVH6J9vwv_wNiIv1rDl6KD2U-aGjfLVxa2S46qrbDzOGJIDMA5RiJHVv2M_galf1g.webp",
            bannerImage: "",
            video: ""
        }
    ]
};

export default data;